default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fumotoyuta
  password: Fyfms.6228

development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: fumotoyuta
  password: <%= ENV['MY_PROJECT_DATABASE_PASSWORD'] %>